name: Build and Push Container to ECR

on:
  workflow_dispatch:
  push:
    branches: [main]

env:
  GITHUB_SHA: ${{ github.sha }}
  FUNCTION_NAME: next_lambda_function
  REGISTRY: 545719101351.dkr.ecr.ca-central-1.amazonaws.com/next-auth-sandbox-wm/web

jobs:
  build-push-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - name: Configure AWS credentials using Access Key ID and Secret Access Key
        uses: aws-actions/configure-aws-credentials@010d0da01d0b5a38af31e9c3470dbfdabdecca3a # v4.0.1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ca-central-1

      - name: Build Container
        run: |
          docker build \
          --build-arg git_sha=$GITHUB_SHA \
          --secret id=OKTA_OAUTH2_CLIENT_ID,env=${{ secrets.OKTA_OAUTH2_CLIENT_ID }} \
          --secret id=OKTA_OAUTH2_CLIENT_SECRET,env=${{ secrets.OKTA_OAUTH2_CLIENT_SECRET }} \
          --secret id=SECRET,env=${{ secrets.SECRET }} \
          -t ${{ env.REGISTRY }}:$GITHUB_SHA \
          -t ${{ env.REGISTRY }}:latest .

      - name: Login to ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@9149ade017c57f86dea2f76a01f8b2d5bd06b10f # tag=v1.5.1

      - name: Push containers to ECR
        run: |
          docker push ${{ env.REGISTRY }}:$GITHUB_SHA
          docker push ${{ env.REGISTRY }}:latest

      - name: Deploy new image
        run: |
          aws lambda update-function-code \
            --function-name $FUNCTION_NAME \
            --image-uri ${{ env.REGISTRY }}:$GITHUB_SHA > /dev/null 2>&1

      - name: Logout of Amazon ECR
        run: docker logout ${{ steps.login-ecr.outputs.registry }}
