name: Node CI/CD

on:  
  pull_request:
    branches:
      - main

env:
  NODE_VERSION: 18

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{env.NODE_VERSION}}
      uses: actions/setup-node@v1
      with:
        node-version: ${{env.NODE_VERSION}}
    - name: yarn install and build
      run: |
        yarn install
        yarn build
      env:
        CI: true