name: "Terraform Apply Production"

on:
  push:
    branches:
      - main
    paths:
      - "terragrunt/**"
      - ".github/workflows/tf_apply_production.yml"

env:
  AWS_REGION: ca-central-1
  TERRAFORM_VERSION: 1.3.9
  TERRAGRUNT_VERSION: 0.44.4
  CONFTEST_VERSION: 0.27.0

permissions:
  id-token: write
  contents: read
  pull-requests: write
  actions: write
  checks: write
  statuses: write
  
jobs:
  terragrunt-apply:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # tag=v3.0.2

      - name: setup terraform tools
        uses: cds-snc/terraform-tools-setup@v1

     - name: Configure AWS credentials using Access Key ID and Secret Access Key
        uses: aws-actions/configure-aws-credentials@8c3f20df09ac63af7b3ae3d7c91f105f857d8497 # v4.0.0
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ca-central-1

      - name: Terraform Apply
        working-directory: terragrunt/env
        run: terragrunt apply --terragrunt-non-interactive -auto-approve